In [1]:
#Nạp thư viện
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
#

In [2]:
dataset = pd.read_csv('/content/advertising.csv')

In [3]:
dataset.head(5)

,Daily Time Spent on Site,Age,Area Income,Daily Internet Usage,Ad Topic Line,City,Male,Country,Timestamp,Clicked on Ad
0,68.95,35,61833.90,256.09,Cloned 5thgeneration orchestration,Wrightburgh,0,Tunisia,2016-03-27 00:53:11,0
1,80.23,31,68441.85,193.77,Monitored national standardization,West Jodi,1,Nauru,2016-04-04 01:39:02,0
2,69.47,26,59785.94,236.50,Organic bottom-line service-desk,Davidton,0,San Marino,2016-03-13 20:35:42,0
3,74.15,29,54806.18,245.89,Triple-buffered reciprocal time-frame,West Terrifurt,1,Italy,2016-01-10 02:31:19,0
4,68.37,35,73889.99,225.58,Robust logistical utilization,South Manuel,0,Iceland,2016-06-03 03:36:18,0

In [5]:
dataset.describe()

,Daily Time Spent on Site,Age,Area Income,Daily Internet Usage,Male,Clicked on Ad
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.00000
mean,65.000200,36.009000,55000.000080,180.000100,0.481000,0.50000
std,15.853615,8.785562,13414.634022,43.902339,0.499889,0.50025
min,32.600000,19.000000,13996.500000,104.780000,0.000000,0.00000
25%,51.360000,29.000000,47031.802500,138.830000,0.000000,0.00000
50%,68.215000,35.000000,57012.300000,183.130000,0.000000,0.50000
75%,78.547500,42.000000,65470.635000,218.792500,1.000000,1.00000
max,91.430000,61.000000,79484.800000,269.960000,1.000000,1.00000

In [6]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Daily Time Spent on Site  1000 non-null   float64
 1   Age                       1000 non-null   int64
 2   Area Income               1000 non-null   float64
 3   Daily Internet Usage      1000 non-null   float64
 4   Ad Topic Line             1000 non-null   object
 5   City                      1000 non-null   object
 6   Male                      1000 non-null   int64
 7   Country                   1000 non-null   object
 8   Timestamp                 1000 non-null   object
 9   Clicked on Ad             1000 non-null   int64
dtypes: float64(3), int64(3), object(4)
memory usage: 78.3+ KB

In [8]:
#xử lý timestamp
dataset['Timestamp'] = pd.to_datetime(dataset['Timestamp'])

dataset['Hour'] = dataset['Timestamp'].dt.hour
dataset['day_of_week'] = dataset['Timestamp'].dt.dayofweek
dataset['month'] = dataset['Timestamp'].dt.month

dataset.head(5)

,Daily Time Spent on Site,Age,Area Income,Daily Internet Usage,Ad Topic Line,City,Male,Country,Timestamp,Clicked on Ad,Hour,day_of_week,month
0,68.95,35,61833.90,256.09,Cloned 5thgeneration orchestration,Wrightburgh,0,Tunisia,2016-03-27 00:53:11,0,0,6,3
1,80.23,31,68441.85,193.77,Monitored national standardization,West Jodi,1,Nauru,2016-04-04 01:39:02,0,1,0,4
2,69.47,26,59785.94,236.50,Organic bottom-line service-desk,Davidton,0,San Marino,2016-03-13 20:35:42,0,20,6,3
3,74.15,29,54806.18,245.89,Triple-buffered reciprocal time-frame,West Terrifurt,1,Italy,2016-01-10 02:31:19,0,2,6,1
4,68.37,35,73889.99,225.58,Robust logistical utilization,South Manuel,0,Iceland,2016-06-03 03:36:18,0,3,4,6

In [9]:
dataset= dataset.drop(columns=['Timestamp'])
dataset.head(5)

,Daily Time Spent on Site,Age,Area Income,Daily Internet Usage,Ad Topic Line,City,Male,Country,Clicked on Ad,Hour,day_of_week,month
0,68.95,35,61833.90,256.09,Cloned 5thgeneration orchestration,Wrightburgh,0,Tunisia,0,0,6,3
1,80.23,31,68441.85,193.77,Monitored national standardization,West Jodi,1,Nauru,0,1,0,4
2,69.47,26,59785.94,236.50,Organic bottom-line service-desk,Davidton,0,San Marino,0,20,6,3
3,74.15,29,54806.18,245.89,Triple-buffered reciprocal time-frame,West Terrifurt,1,Italy,0,2,6,1
4,68.37,35,73889.99,225.58,Robust logistical utilization,South Manuel,0,Iceland,0,3,4,6

In [11]:
from sklearn.preprocessing import StandardScaler
#Scale dữ liệu
num_cols = [
'Daily Time Spent on Site',
'Age',
'Area Income',
'Daily Internet Usage',
'hour',
'day_of_week',
'month'
]
dataset.head(5)

,Daily Time Spent on Site,Age,Area Income,Daily Internet Usage,Ad Topic Line,City,Male,Country,Clicked on Ad,Hour,day_of_week,month
0,68.95,35,61833.90,256.09,Cloned 5thgeneration orchestration,Wrightburgh,0,Tunisia,0,0,6,3
1,80.23,31,68441.85,193.77,Monitored national standardization,West Jodi,1,Nauru,0,1,0,4
2,69.47,26,59785.94,236.50,Organic bottom-line service-desk,Davidton,0,San Marino,0,20,6,3
3,74.15,29,54806.18,245.89,Triple-buffered reciprocal time-frame,West Terrifurt,1,Italy,0,2,6,1
4,68.37,35,73889.99,225.58,Robust logistical utilization,South Manuel,0,Iceland,0,3,4,6

In [12]:
#xỬ Lý text
from sklearn.feature_extraction.text import TfidfVectorizer

TfidfVectorizer(
    max_features=1000,
    stop_words='english',
    ngram_range=(1,2)
)

TfidfVectorizer(max_features=1000, ngram_range=(1, 2), stop_words='english')

In [13]:
#Xử lý biến categorical
for col in ['City','Country']:
    freq = dataset[col].value_counts()
    dataset[col] = dataset[col].map(freq)

In [14]:
dataset.head(5)

,Daily Time Spent on Site,Age,Area Income,Daily Internet Usage,Ad Topic Line,City,Male,Country,Clicked on Ad,Hour,day_of_week,month
0,68.95,35,61833.90,256.09,Cloned 5thgeneration orchestration,2,0,4,0,0,6,3
1,80.23,31,68441.85,193.77,Monitored national standardization,1,1,3,0,1,0,4
2,69.47,26,59785.94,236.50,Organic bottom-line service-desk,1,0,3,0,20,6,3
3,74.15,29,54806.18,245.89,Triple-buffered reciprocal time-frame,1,1,5,0,2,6,1
4,68.37,35,73889.99,225.58,Robust logistical utilization,1,0,3,0,3,4,6

In [16]:
X = dataset.drop(columns='Clicked on Ad')
y = dataset['Clicked on Ad']

0    0
1    0
2    0
3    0
4    0
Name: Clicked on Ad, dtype: int64

In [17]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=0)

In [20]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression

num_features = [
'Daily Time Spent on Site',
'Age',
'Area Income',
'Daily Internet Usage',
'Hour', # Changed 'hour' to 'Hour'
'day_of_week',
'month',
'City',
'Country'
]

preprocess = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), num_features),
        ('text', TfidfVectorizer(max_features=1000, ngram_range=(1,2)), 'Ad Topic Line'),
        ('bin', 'passthrough', ['Male'])
    ]
)

model = Pipeline([
    ('prep', preprocess),
    ('clf', LogisticRegression(penalty='l2', max_iter=1000))
])

In [21]:
model.fit(X_train,y_train)

Pipeline(steps=[('prep',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['Daily Time Spent on Site',
                                                   'Age', 'Area Income',
                                                   'Daily Internet Usage',
                                                   'Hour', 'day_of_week',
                                                   'month', 'City',
                                                   'Country']),
                                                 ('text',
                                                  TfidfVectorizer(max_features=1000,
                                                                  ngram_range=(1,
                                                                               2)),
                                                  'Ad Topic Line'),
                                                 ('bin', 'passthrough',
                                                  ['Male'])])),
                ('clf', LogisticRegression(max_iter=1000))])

In [22]:
y_prob = model.predict_proba(X_test)[:,1]
y_pred = model.predict(X_test)

In [23]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
print(f'Accuracy: {accuracy:.2f}')
print(f'Precision: {precision:.2f}')
print(f'Recall: {recall:.2f}')
print(f'F1 Score: {f1:.2f}')

Accuracy: 0.97
Precision: 0.98
Recall: 0.96
F1 Score: 0.97